changes in test

diff --git a/.github/workflows/int_test.yml b/.github/workflows/int_test.yml
--- a/.github/workflows/int_test.yml
+++ b/.github/workflows/int_test.yml
@@ -46,11 +46,13 @@ jobs:
                 sleep 10
                 mysql -u root -p"root" -e "CREATE DATABASE IF NOT EXISTS webapp;"
 
+            # - name: Run Integration tests
+            #   run: |
+            #     if npm run test:integration; then
+            #       echo "Tests passed successfully."
+            #     else
+            #       echo "Tests failed."
+            #       exit 1
+            #     fi
             - name: Run Integration tests
-              run: |
-                if npm run test:integration; then
-                  echo "Tests passed successfully."
-                else
-                  echo "Tests failed."
-                  exit 1
-                fi
+            run : npm run test:integration || exit 1
